---
title: "Know Your Audience, Choose Your Stage"
output:
  word_document: default
  html_notebook: default
  pdf_document: default
  html_document:
    df_print: paged
---

```{r include = FALSE}
library(lme4)
library(lmerTest)
library(emmeans)
```
## 1. Experimental Overview

Animal behavior is often modified by the animal's environment. This includes both the physical environment (substrate, spatial complexity, etc.) and the social environment, such as mates, family groups, or unrelated members of a herd. The effects of both the physical and social environment on behavior have been well studied in isolation, but rarely in combination. 

I propose to examine the interaction of spatial complexity and social environment on dominance interactions in the Amazon molly, a naturally genetically clonal (and all female) species of fish. In addition to being clones, these fish are a useful study system to study dominance interactions as fish of the same size will reliably engage in fights for dominance.

Fish will be placed in groups of 8 size-matched fish and allowed to become familiar over 3 weeks. After this, a pair will be randomly selected and placed into separate acclimation chambers within a Dominance Interaction tank. This tank will either have a covering which obscures 1/2 of the tank (Complex) or be completely open and visible (Simple). The remainder of the group OR an unfamiliar group of 6 fish (of similar size) will be placed in an adjacent Audience Tank, where they will be allowed to observe the pair in the Dominance Interaction tank. Fish are readily able to view each other tank to tank (except when the barrier is in place, which obscures 1/2 of the view).

After the acclimation period, the dominance pair will be released from their chambers and allowed to fight for 5 minutes. Aggressive acts (bites, tail beats, and chases) will be recorded and combined to create a single "Aggression" score for the pair's interaction.

## 2. Design Table

| Structure | Variable        | Type    | #levels | EU              |
|-----------|-----------------|---------|---------|-----------------|
| Treatment | Audience        | Cat     | 2       | Group:Aud       |
|           | Tank Complexity | Cat     | 2       | Group:Comp      |
|           | Aud:Comp        | Cat     | 4       | Group:Aud:Comp  |
| Design    | Group:Aud       | Cat     | 8       |                 |
|           | Group:Comp      | Cat     | 8       |                 |
|           | Group:Aud:Comp  | Cat     | 16      |                 |
|           | Group           | Cat     | 4       |                 |
|           | Pair            | Cat     | 16      |                 |
|           | Pair:Aud        | Cat     | 16      |                 |
|           | Pair:Comp       | Cat     | 16      |                 | # nested subsample
|           | Pair:Aud:Comp   | Cat     | 16      |                 | # aliased
| Response  | Aggression      | Numeric | 16      |                 |

> Because the treatment of familarity is only uniformly applied at the Group level, I have chosen Group as the EU. Group is also a block, as each "familar audience" treatment is necessarily different for each Group. Pair can also be considered a block, but is nested within Group.


## 3. Linear model

> mollymolly_model <- lmer(Aggression ~ Aud + Comp + Aud:Comp + Group + (1|Group:Aud) + (1|Group:Comp) + (1|Group:Aud:Comp) + Pair + (1|Pair:Aud) + (1|Pair:Comp) + (1|Pair:Aud:Comp))


## 4. Effect Estimates

> Using an ANOVA (and the emmip() function), I will compare the treatment effect estimates of Familiar vs. Unfamiliar, Complex vs. Simple, and the interaction of the two (Aud:Comp) to determine if there is evidence of an effect of Audience, Complexity, or an interaction of the two, on Aggression (units = mean Aggression).

> Example Statement: We found that there was a significant interaction between Tank Complexity and Audience Familiarity. An unfamiliar audience always decreased aggression relative to a familiar audience (p-value = 0.001). However, tank complexity varied depending on the audience familiarity, with unfamiliar audiences and simple tanks leading to the largest decrease in aggression relative to the other treatment combinations.

## 5. Blocking

> My experiment will be a Complete Block Design, as every treatment combination occurs in every Group. There is a possibility that the Groups I create will have different collective behavior (and thus, Pair behavior), so I need to have several separate Groups to control for any variation inherent in the Group. In an ideal world, I would have more replicates within a group, but it is unlikely that I will have enough fish of the same size to create groups of 16 or more (2 pairs with each treatment combo). I plan on re-assessing as I get closer to experiment execution and determining whether an Incomplete Block Design is feasible with the fish I have available.